package com.relative.brecreditosnuevos.objetosnegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Opcion implements java.io.Serializable {

	static final long serialVersionUID = 1L;
	@org.kie.api.definition.type.Label("Plazo")
	private Integer Plazo;
	@org.kie.api.definition.type.Label("PeriodoPlazo")
	private String PeriodoPlazo;
	@org.kie.api.definition.type.Label("PeriodicidadPlazo")
	private String PeriodicidadPlazo;
	@org.kie.api.definition.type.Label("MontoFinanciado")
	private Double MontoFinanciado;
	@org.kie.api.definition.type.Label("ValorARecibir")
	private Double ValorARecibir;
	@org.kie.api.definition.type.Label("ValorAPagar")
	private Double ValorAPagar;
	@org.kie.api.definition.type.Label("CostoCustodia")
	private Double CostoCustodia;
	@org.kie.api.definition.type.Label("CostoFideicomiso")
	private Double CostoFideicomiso;
	@org.kie.api.definition.type.Label("CostoSeguro")
	private Double CostoSeguro;
	@org.kie.api.definition.type.Label("CostoTasacion")
	private Double CostoTasacion;
	@org.kie.api.definition.type.Label("CostoTransporte")
	private Double CostoTransporte;
	@org.kie.api.definition.type.Label("CostoValoracion")
	private Double CostoValoracion;
	@org.kie.api.definition.type.Label("FormaPagoCapital")
	private String FormaPagoCapital;
	@org.kie.api.definition.type.Label("FormaPagoCustodia")
	private String FormaPagoCustodia;
	@org.kie.api.definition.type.Label("FormaPagoFideicomiso")
	private String FormaPagoFideicomiso;
	@org.kie.api.definition.type.Label("FormaPagoInteres")
	private String FormaPagoInteres;
	@org.kie.api.definition.type.Label("FormaPagoMora")
	private String FormaPagoMora;
	@org.kie.api.definition.type.Label("FormaPagoGastoCobranza")
	private String FormaPagoGastoCobranza;
	@org.kie.api.definition.type.Label("FormaPagoSeguro")
	private String FormaPagoSeguro;
	@org.kie.api.definition.type.Label("FormaPagoTasador")
	private String FormaPagoTasador;
	@org.kie.api.definition.type.Label("FormaPagoTransporte")
	private String FormaPagoTransporte;
	@org.kie.api.definition.type.Label("FormaPagoValoracion")
	private String FormaPagoValoracion;
	@org.kie.api.definition.type.Label("SaldoInteres")
	private Double SaldoInteres;
	@org.kie.api.definition.type.Label("SaldoMora")
	private Double SaldoMora;
	@org.kie.api.definition.type.Label("GastoCobranza")
	private Double GastoCobranza;
	@org.kie.api.definition.type.Label("Cuota")
	private Double Cuota;
	@org.kie.api.definition.type.Label("SaldoCapitalRenov")
	private Double SaldoCapitalRenov;
	@org.kie.api.definition.type.Label("MontoPrevioDesembolso")
	private Double MontoPrevioDesembolso;
	@org.kie.api.definition.type.Label("TotalGastosNuevaOperacion")
	private Double TotalGastosNuevaOperacion;
	@org.kie.api.definition.type.Label("TotalCostosOperacionAnterior")
	private Double TotalCostosOperacionAnterior;

	public Opcion() {
	}

	// Getter Methods

	public Integer getPlazo() {
		return Plazo;
	}

	public String getPeriodoPlazo() {
		return PeriodoPlazo;
	}

	public String getPeriodicidadPlazo() {
		return PeriodicidadPlazo;
	}

	public Double getMontoFinanciado() {
		return MontoFinanciado;
	}

	public Double getValorARecibir() {
		return ValorARecibir;
	}

	public Double getValorAPagar() {
		return ValorAPagar;
	}

	public Double getCostoCustodia() {
		return CostoCustodia;
	}

	public Double getCostoFideicomiso() {
		return CostoFideicomiso;
	}

	public Double getCostoSeguro() {
		return CostoSeguro;
	}

	public Double getCostoTasacion() {
		return CostoTasacion;
	}

	public Double getCostoTransporte() {
		return CostoTransporte;
	}

	public Double getCostoValoracion() {
		return CostoValoracion;
	}

	public String getFormaPagoCapital() {
		return FormaPagoCapital;
	}

	public String getFormaPagoCustodia() {
		return FormaPagoCustodia;
	}

	public String getFormaPagoFideicomiso() {
		return FormaPagoFideicomiso;
	}

	public String getFormaPagoInteres() {
		return FormaPagoInteres;
	}

	public String getFormaPagoMora() {
		return FormaPagoMora;
	}

	public String getFormaPagoGastoCobranza() {
		return FormaPagoGastoCobranza;
	}

	public String getFormaPagoSeguro() {
		return FormaPagoSeguro;
	}

	public String getFormaPagoTasador() {
		return FormaPagoTasador;
	}

	public String getFormaPagoTransporte() {
		return FormaPagoTransporte;
	}

	public String getFormaPagoValoracion() {
		return FormaPagoValoracion;
	}

	public Double getSaldoInteres() {
		return SaldoInteres;
	}

	public Double getSaldoMora() {
		return SaldoMora;
	}

	public Double getGastoCobranza() {
		return GastoCobranza;
	}

	public Double getCuota() {
		return Cuota;
	}

	public Double getSaldoCapitalRenov() {
		return SaldoCapitalRenov;
	}

	public Double getMontoPrevioDesembolso() {
		return MontoPrevioDesembolso;
	}

	public Double getTotalGastosNuevaOperacion() {
		return TotalGastosNuevaOperacion;
	}

	public Double getTotalCostosOperacionAnterior() {
		return TotalCostosOperacionAnterior;
	}

	// Setter Methods

	public void setPlazo(Integer Plazo) {
		this.Plazo = Plazo;
	}

	public void setPeriodoPlazo(String PeriodoPlazo) {
		this.PeriodoPlazo = PeriodoPlazo;
	}

	public void setPeriodicidadPlazo(String PeriodicidadPlazo) {
		this.PeriodicidadPlazo = PeriodicidadPlazo;
	}

	public void setMontoFinanciado(Double MontoFinanciado) {
		this.MontoFinanciado = MontoFinanciado;
	}

	public void setValorARecibir(Double ValorARecibir) {
		this.ValorARecibir = ValorARecibir;
	}

	public void setValorAPagar(Double ValorAPagar) {
		this.ValorAPagar = ValorAPagar;
	}

	public void setCostoCustodia(Double CostoCustodia) {
		this.CostoCustodia = CostoCustodia;
	}

	public void setCostoFideicomiso(Double CostoFideicomiso) {
		this.CostoFideicomiso = CostoFideicomiso;
	}

	public void setCostoSeguro(Double CostoSeguro) {
		this.CostoSeguro = CostoSeguro;
	}

	public void setCostoTasacion(Double CostoTasacion) {
		this.CostoTasacion = CostoTasacion;
	}

	public void setCostoTransporte(Double CostoTransporte) {
		this.CostoTransporte = CostoTransporte;
	}

	public void setCostoValoracion(Double CostoValoracion) {
		this.CostoValoracion = CostoValoracion;
	}

	public void setFormaPagoCapital(String FormaPagoCapital) {
		this.FormaPagoCapital = FormaPagoCapital;
	}

	public void setFormaPagoCustodia(String FormaPagoCustodia) {
		this.FormaPagoCustodia = FormaPagoCustodia;
	}

	public void setFormaPagoFideicomiso(String FormaPagoFideicomiso) {
		this.FormaPagoFideicomiso = FormaPagoFideicomiso;
	}

	public void setFormaPagoInteres(String FormaPagoInteres) {
		this.FormaPagoInteres = FormaPagoInteres;
	}

	public void setFormaPagoMora(String FormaPagoMora) {
		this.FormaPagoMora = FormaPagoMora;
	}

	public void setFormaPagoGastoCobranza(String FormaPagoGastoCobranza) {
		this.FormaPagoGastoCobranza = FormaPagoGastoCobranza;
	}

	public void setFormaPagoSeguro(String FormaPagoSeguro) {
		this.FormaPagoSeguro = FormaPagoSeguro;
	}

	public void setFormaPagoTasador(String FormaPagoTasador) {
		this.FormaPagoTasador = FormaPagoTasador;
	}

	public void setFormaPagoTransporte(String FormaPagoTransporte) {
		this.FormaPagoTransporte = FormaPagoTransporte;
	}

	public void setFormaPagoValoracion(String FormaPagoValoracion) {
		this.FormaPagoValoracion = FormaPagoValoracion;
	}

	public void setSaldoInteres(Double SaldoInteres) {
		this.SaldoInteres = SaldoInteres;
	}

	public void setSaldoMora(Double SaldoMora) {
		this.SaldoMora = SaldoMora;
	}

	public void setGastoCobranza(Double GastoCobranza) {
		this.GastoCobranza = GastoCobranza;
	}

	public void setCuota(Double Cuota) {
		this.Cuota = Cuota;
	}

	public void setSaldoCapitalRenov(Double SaldoCapitalRenov) {
		this.SaldoCapitalRenov = SaldoCapitalRenov;
	}

	public void setMontoPrevioDesembolso(Double MontoPrevioDesembolso) {
		this.MontoPrevioDesembolso = MontoPrevioDesembolso;
	}

	public void setTotalGastosNuevaOperacion(Double TotalGastosNuevaOperacion) {
		this.TotalGastosNuevaOperacion = TotalGastosNuevaOperacion;
	}

	public void setTotalCostosOperacionAnterior(
			Double TotalCostosOperacionAnterior) {
		this.TotalCostosOperacionAnterior = TotalCostosOperacionAnterior;
	}

	public Opcion(java.lang.Integer Plazo, java.lang.String PeriodoPlazo,
			java.lang.String PeriodicidadPlazo,
			java.lang.Double MontoFinanciado, java.lang.Double ValorARecibir,
			java.lang.Double ValorAPagar, java.lang.Double CostoCustodia,
			java.lang.Double CostoFideicomiso, java.lang.Double CostoSeguro,
			java.lang.Double CostoTasacion, java.lang.Double CostoTransporte,
			java.lang.Double CostoValoracion,
			java.lang.String FormaPagoCapital,
			java.lang.String FormaPagoCustodia,
			java.lang.String FormaPagoFideicomiso,
			java.lang.String FormaPagoInteres, java.lang.String FormaPagoMora,
			java.lang.String FormaPagoGastoCobranza,
			java.lang.String FormaPagoSeguro,
			java.lang.String FormaPagoTasador,
			java.lang.String FormaPagoTransporte,
			java.lang.String FormaPagoValoracion,
			java.lang.Double SaldoInteres, java.lang.Double SaldoMora,
			java.lang.Double GastoCobranza, java.lang.Double Cuota,
			java.lang.Double SaldoCapitalRenov,
			java.lang.Double MontoPrevioDesembolso,
			java.lang.Double TotalGastosNuevaOperacion,
			java.lang.Double TotalCostosOperacionAnterior) {
		this.Plazo = Plazo;
		this.PeriodoPlazo = PeriodoPlazo;
		this.PeriodicidadPlazo = PeriodicidadPlazo;
		this.MontoFinanciado = MontoFinanciado;
		this.ValorARecibir = ValorARecibir;
		this.ValorAPagar = ValorAPagar;
		this.CostoCustodia = CostoCustodia;
		this.CostoFideicomiso = CostoFideicomiso;
		this.CostoSeguro = CostoSeguro;
		this.CostoTasacion = CostoTasacion;
		this.CostoTransporte = CostoTransporte;
		this.CostoValoracion = CostoValoracion;
		this.FormaPagoCapital = FormaPagoCapital;
		this.FormaPagoCustodia = FormaPagoCustodia;
		this.FormaPagoFideicomiso = FormaPagoFideicomiso;
		this.FormaPagoInteres = FormaPagoInteres;
		this.FormaPagoMora = FormaPagoMora;
		this.FormaPagoGastoCobranza = FormaPagoGastoCobranza;
		this.FormaPagoSeguro = FormaPagoSeguro;
		this.FormaPagoTasador = FormaPagoTasador;
		this.FormaPagoTransporte = FormaPagoTransporte;
		this.FormaPagoValoracion = FormaPagoValoracion;
		this.SaldoInteres = SaldoInteres;
		this.SaldoMora = SaldoMora;
		this.GastoCobranza = GastoCobranza;
		this.Cuota = Cuota;
		this.SaldoCapitalRenov = SaldoCapitalRenov;
		this.MontoPrevioDesembolso = MontoPrevioDesembolso;
		this.TotalGastosNuevaOperacion = TotalGastosNuevaOperacion;
		this.TotalCostosOperacionAnterior = TotalCostosOperacionAnterior;
	}
}