package com.relative.brecreditosnuevos.objetosnegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VariablesNegocio implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("TotalGarantia")
	private java.lang.Double totalGarantia;
	@org.kie.api.definition.type.Label("TotalPeso")
	private java.lang.Double totalPeso;

	@org.kie.api.definition.type.Label("PrecioGramo")
	private java.lang.Double precioGramo;

	@org.kie.api.definition.type.Label("Mensaje")
	private java.lang.String mensaje;

	@org.kie.api.definition.type.Label("Detener")
	private java.lang.Boolean detener;

	@org.kie.api.definition.type.Label("TotalServicios")
	private java.lang.Double totalServicios;

	@org.kie.api.definition.type.Label("PerfilInternoNuerico")
	private java.lang.Integer perfilInternoNuerico;

	@org.kie.api.definition.type.Label("DetenerColateral")
	private java.lang.Boolean detenerColateral;

	@org.kie.api.definition.type.Label("DetenerColateralAdicional")
	private java.lang.Boolean detenerColateralAdicional;

	@org.kie.api.definition.type.Label("MensajeBloqueo")
	private java.lang.String mensajeBloqueo;

	@org.kie.api.definition.type.Label("MensajeVinculadoQuski")
	private java.lang.String mensajeVinculadoQuski;

	@org.kie.api.definition.type.Label("MensajeImpagoQuski")
	private java.lang.String mensajeImpagoQuski;

	@org.kie.api.definition.type.Label("CodigoPoliticaBloqueo")
	private java.lang.String codigoPoliticaBloqueo;

	@org.kie.api.definition.type.Label("Politica")
	private java.lang.String politica;

	@org.kie.api.definition.type.Label("CodigoPolitica")
	private java.util.List<java.lang.String> codigoPolitica;

	public VariablesNegocio() {
	}

	public java.lang.Double getTotalGarantia() {
		return this.totalGarantia;
	}

	public void setTotalGarantia(java.lang.Double totalGarantia) {
		this.totalGarantia = totalGarantia;
	}

	public java.lang.Double getTotalPeso() {
		return this.totalPeso;
	}

	public void setTotalPeso(java.lang.Double totalPeso) {
		this.totalPeso = totalPeso;
	}

	public java.lang.Double getPrecioGramo() {
		return this.precioGramo;
	}

	public void setPrecioGramo(java.lang.Double precioGramo) {
		this.precioGramo = precioGramo;
	}

	public java.lang.String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(java.lang.String mensaje) {
		this.mensaje = mensaje;
	}

	public java.lang.Boolean getDetener() {
		return this.detener;
	}

	public void setDetener(java.lang.Boolean detener) {
		this.detener = detener;
	}

	public java.lang.Double getTotalServicios() {
		return this.totalServicios;
	}

	public void setTotalServicios(java.lang.Double totalServicios) {
		this.totalServicios = totalServicios;
	}

	public java.lang.Integer getPerfilInternoNuerico() {
		return this.perfilInternoNuerico;
	}

	public void setPerfilInternoNuerico(java.lang.Integer perfilInternoNuerico) {
		this.perfilInternoNuerico = perfilInternoNuerico;
	}

	public java.lang.Boolean getDetenerColateral() {
		return this.detenerColateral;
	}

	public void setDetenerColateral(java.lang.Boolean detenerColateral) {
		this.detenerColateral = detenerColateral;
	}

	public java.lang.Boolean getDetenerColateralAdicional() {
		return this.detenerColateralAdicional;
	}

	public void setDetenerColateralAdicional(
			java.lang.Boolean detenerColateralAdicional) {
		this.detenerColateralAdicional = detenerColateralAdicional;
	}

	public java.lang.String getMensajeBloqueo() {
		return this.mensajeBloqueo;
	}

	public void setMensajeBloqueo(java.lang.String mensajeBloqueo) {
		this.mensajeBloqueo = mensajeBloqueo;
	}

	public java.lang.String getMensajeVinculadoQuski() {
		return this.mensajeVinculadoQuski;
	}

	public void setMensajeVinculadoQuski(java.lang.String mensajeVinculadoQuski) {
		this.mensajeVinculadoQuski = mensajeVinculadoQuski;
	}

	public java.lang.String getMensajeImpagoQuski() {
		return this.mensajeImpagoQuski;
	}

	public void setMensajeImpagoQuski(java.lang.String mensajeImpagoQuski) {
		this.mensajeImpagoQuski = mensajeImpagoQuski;
	}

	public java.lang.String getCodigoPoliticaBloqueo() {
		return this.codigoPoliticaBloqueo;
	}

	public void setCodigoPoliticaBloqueo(java.lang.String codigoPoliticaBloqueo) {
		this.codigoPoliticaBloqueo = codigoPoliticaBloqueo;
	}

	public java.lang.String getPolitica() {
		return this.politica;
	}

	public void setPolitica(java.lang.String politica) {
		this.politica = politica;
	}

	public java.util.List<java.lang.String> getCodigoPolitica() {
		return this.codigoPolitica;
	}

	public void setCodigoPolitica(
			java.util.List<java.lang.String> codigoPolitica) {
		this.codigoPolitica = codigoPolitica;
	}

	public VariablesNegocio(java.lang.Double totalGarantia,
			java.lang.Double totalPeso, java.lang.Double precioGramo,
			java.lang.String mensaje, java.lang.Boolean detener,
			java.lang.Double totalServicios,
			java.lang.Integer perfilInternoNuerico,
			java.lang.Boolean detenerColateral,
			java.lang.Boolean detenerColateralAdicional,
			java.lang.String mensajeBloqueo,
			java.lang.String mensajeVinculadoQuski,
			java.lang.String mensajeImpagoQuski,
			java.lang.String codigoPoliticaBloqueo, java.lang.String politica,
			java.util.List<java.lang.String> codigoPolitica) {
		this.totalGarantia = totalGarantia;
		this.totalPeso = totalPeso;
		this.precioGramo = precioGramo;
		this.mensaje = mensaje;
		this.detener = detener;
		this.totalServicios = totalServicios;
		this.perfilInternoNuerico = perfilInternoNuerico;
		this.detenerColateral = detenerColateral;
		this.detenerColateralAdicional = detenerColateralAdicional;
		this.mensajeBloqueo = mensajeBloqueo;
		this.mensajeVinculadoQuski = mensajeVinculadoQuski;
		this.mensajeImpagoQuski = mensajeImpagoQuski;
		this.codigoPoliticaBloqueo = codigoPoliticaBloqueo;
		this.politica = politica;
		this.codigoPolitica = codigoPolitica;
	}

}